name: race_fueling_cli
description: CLI interface for the Race Fueling Calculator
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  race_fueling_core:
    path: ../core
  args: ^2.6.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.8
  lints: ^5.1.1
